@cleanArchitecture_HostAddress = http://localhost:5084

POST {{cleanArchitecture_HostAddress}}/api/supporttickets
Content-Type: application/json

{
  "title": "Mouse not working",
  "description": "Unplugged maybe?"
}
